\documentclass{article}
\usepackage{Sweave}
\usepackage{tabularx}
\usepackage{geometry}
\geometry{margin=.5in}
\usepackage{enumerate}
\usepackage[demo]{graphicx}
\makeatletter
\setlength{\@fptop}{0pt}
\makeatother
\begin{document}

<<figs.only=TRUE,echo=FALSE,message=FALSE,warning=FALSE>>=
###This is a tidy analysis compiling and comparing all of Dan B's hysteranthy codes from elsewhere
###Began 5 Spet 2017

rm(list=ls()) 
options(stringsAsFactors = FALSE)
graphics.off()
setwd("~/Documents/git/proterant/input")
library(ape)
library(phytools)
library(geiger)
library(gbm)
library(pez)
library(dplyr)
library(tidyr)
library(caper)
library(picante)
library(tidyverse)
library(boot)
library(phylolm)
library(ggplot2)

#########READ IN ALL DATA AND ASSOCIATED TREES##################

mich.tree<-read.tree("pruned_for_mich.tre")
mich.data<-read.csv("mich_data_full.csv")

silv.tree<-read.tree("pruned_silvics.tre")
silv.data<-read.csv("silv_data_full.csv")

#keeler.tree<-read.tree("pruned_keeler.tre")
#keeler.data<-read.csv("keeler_cleaned.csv")

#setdiff(keeler.data$name,mich.data$name)
#clean av fruit time
mich.data$av_fruit_time[mich.data$av_fruit_time=="persistant"]<-12
mich.data$av_fruit_time[mich.data$av_fruit_time=="persitant"]<-12
mich.data$av_fruit_time[mich.data$av_fruit_time=="unreported"]<-9    
mich.data$av_fruit_time<-as.numeric(mich.data$av_fruit_time)

###clean fruiting
#mich.data$fruiting[mich.data$fruiting==19]<-7

#####add a new column for a adjusting for red acorn time
mich.data$fruiting<-NA
mich.data$fruiting<-mich.data$av_fruit_time
mich.data$fruiting[mich.data$fruiting==19]<-7
mich.data$fruiting[mich.data$fruiting=="persistant"]<-12
mich.data$fruiting[mich.data$fruiting=="persitant"]<-12
mich.data$fruiting[mich.data$fruiting=="unreported"]<-9                                      
mich.data$fruiting<-as.numeric(mich.data$fruiting)

silv.data$fruiting<-NA
silv.data$fruiting<-silv.data$av_fruit_time
silv.data$fruiting[silv.data$fruiting==21]<-9

#####Centering
mich.data$height_cent<-(mich.data$heigh_height-mean(mich.data$heigh_height))/(2*sd(mich.data$heigh_height))
mich.data$fruit_cent<-(mich.data$fruiting-mean(mich.data$fruiting))/(2*sd(mich.data$fruiting))
mich.data$flo_cent<-(mich.data$flo_time-mean(mich.data$flo_time))/(2*sd(mich.data$flo_time))
mich.data$pol_cent<-(mich.data$pol-mean(mich.data$pol))/(2*sd(mich.data$pol))
mich.data$av_fruit_time_cent<-(mich.data$av_fruit_time-mean(mich.data$av_fruit_time))/(2*sd(mich.data$av_fruit_time))


silv.data$height_cent<-(silv.data$height-mean(silv.data$height))/(2*sd(silv.data$height))
silv.data$fruit_cent<-(silv.data$fruiting-mean(silv.data$fruiting))/(2*sd(silv.data$fruiting))
silv.data$flo_cent<-(silv.data$flower_time-mean(silv.data$flower_time))/(2*sd(silv.data$flower_time))

@

\section*{Introduction}
Hysteranthy, a trait that describes trees that seasonally flower before leafing out, is a common trait in temperate decidious forests. It has been hypothesized that hysteranthy is an adaptation to allow for more effecient wind pollination. An alternative hypothesis posits that hysteranthy is part of an adaptation for early flowering and a product of stronger selection on leaf timing compared to flower timing by late season frost. To begin understand the prevelance and trait associations of hysteranthy, we use published trait data to model the traits the predict hysteranthy.

\section*{Methods}
Data source:\\ Michigan Trees,Michigan shrubs and vines\\ USFS Silvics mannual\\
Tree source: Zanne et al 2014\\
Using R, Modeled hysteranty as a function of other traits, pollination syndrome, shade tolerance, maximum height, timing of flowering, timing of fruiting. We used a pgls model to correct for phylogenetic signal.

\section*{Results}
\begin{figure}[h!]
<<figs.only=TRUE,echo=FALSE,message=FALSE,warning=FALSE>>=
d<-comparative.data(mich.tree,mich.data,name,vcv = TRUE,vcv.dim = 2, na.omit = FALSE)
PhyloD <- phylo.d(d, binvar=pro)
PhyloD

e<-comparative.data(silv.tree,silv.data,name,vcv = TRUE,vcv.dim = 2, na.omit = FALSE)
PhyloE <- phylo.d(e, binvar=pro)
PhyloE

@
\caption{PhyloD for Michigan and Silvics Trees}
\end{figure}

\begin{figure}[h!]
<<figs.only=TRUE,echo=FALSE,message=FALSE,warning=FALSE>>=
mich.data<-  mich.data %>% remove_rownames %>% column_to_rownames(var="name")
silv.data<-  silv.data %>% remove_rownames %>% column_to_rownames(var="name")
mich5cent<-phyloglm(pro~pol+height_cent+flo_cent+fruit_cent+shade_bin,mich.data, mich.tree, method = "logistic_MPLE", btol = 100, log.alpha.bound = 10,start.beta=NULL, start.alpha=NULL,boot=20,full.matrix = TRUE)
summary(mich5cent)
@
\caption{model output for michigan data, centered}
\end{figure}


\begin{figure}[h!]
<<figs.only=TRUE,echo=FALSE,message=FALSE,warning=FALSE>>=
sil5.cent<-phyloglm(pro~pol+flo_cent+height_cent+fruit_cent+shade_bin,silv.data, silv.tree, method = "logistic_MPLE", btol = 60, log.alpha.bound = 4,start.beta=NULL, start.alpha=NULL, boot=20,full.matrix = TRUE)
summary(sil5.cent)
@
\caption{model output for Silvic data, centered}
\end{figure}

\begin{figure}[h!]
\includegraphics[width=21cm, height=15cm]{tree_full_mich.pdf}\\
\caption{Phylogeny and trait map for Michigan data}
\end{figure}

\begin{figure}[h!]
<<figs.only=TRUE,echo=FALSE,message=FALSE,warning=FALSE>>=
library(gridExtra)
est<-as.data.frame(coef(mich5cent))
est<-rownames_to_column(est, "name")
ints<-as.data.frame(confint(mich5cent,level = 0.95))
ints<-rownames_to_column(ints, "name")
colnames(ints)[2] <- "low"
colnames(ints)[3] <- "high"
colnames(est)[2] <- "estimate"
foo<-left_join(est,ints)
foo<-filter(foo,estimate<10)
plotI<-ggplot(foo,aes(estimate,name))+geom_point()+geom_segment(aes(y=name,yend=name,x=low,xend=high))+ggtitle("Main effects of predictors on Hysteranthy: Michigan")+theme_light()+geom_vline(aes(xintercept=0,color="red"))+guides(color="none")

###plot for silvics
est2<-as.data.frame(coef(sil5.cent))
est2<-rownames_to_column(est2, "name")
ints2<-as.data.frame(confint(sil5.cent,level = 0.95))
ints2<-rownames_to_column(ints2, "name")
colnames(ints2)[2] <- "low"
colnames(ints2)[3] <- "high"
colnames(est2)[2] <- "estimate"
foo2<-left_join(est2,ints2)
foo2<-filter(foo2,estimate<10)
plotII<-ggplot(foo2,aes(estimate,name))+geom_point()+geom_segment(aes(y=name,yend=name,x=low,xend=high))+ggtitle("Main effects of predictors on Hysteranthy: SIlvics")+theme_light()+geom_vline(aes(xintercept=0,color="red"))+guides(color="none")
grid.arrange(plotI,plotII, ncol=2)
@
\caption{Trait effect sizes}
\end{figure}


\begin{figure}[h!]
<<figs.only=TRUE,echo=FALSE,message=FALSE,warning=FALSE>>=

plot1<-ggplot(mich.data, aes(x=fruiting, y=pro)) + geom_point(shape=1, position=position_jitter(width=.05,height=.05))  + 
  stat_smooth(method="glm", method.args=list(family="binomial"), se=TRUE)+theme_minimal()

plot2<-ggplot(mich.data, aes(x=flo_time, y=pro)) + geom_point(shape=1, position=position_jitter(width=.05,height=.05)) + 
  stat_smooth(method="glm", method.args=list(family="binomial"), se=TRUE)+theme_minimal()

plot3<-ggplot(mich.data, aes(x=pol, y=pro)) + 
  geom_point(shape=1, position=position_jitter(width=.05,height=.05)) + 
  stat_smooth(method="glm", method.args=list(family="binomial"), se=TRUE)+theme_minimal()

plot4<-ggplot(mich.data, aes(x=shade_bin, y=pro)) + 
  geom_point(shape=1, position=position_jitter(width=.05,height=.05)) + 
  stat_smooth(method="glm", method.args=list(family="binomial"), se=TRUE)+theme_minimal()

plot5<-ggplot(mich.data, aes(x=heigh_height, y=pro)) + 
  geom_point(shape=1, position=position_jitter(width=.05,height=.05)) + 
  stat_smooth(method="glm", method.args=list(family="binomial"), se=TRUE)+theme_minimal()

grid.arrange(plot1, plot2,plot3,plot4,plot5, ncol=2)
@
\caption{Michigan binomial plots}
\end{figure}

\begin{figure}[h!]
<<figs.only=TRUE,echo=FALSE,message=FALSE,warning=FALSE>>=
plot1<-ggplot(silv.data, aes(x=fruiting, y=pro)) + geom_point(shape=1, position=position_jitter(width=.05,height=.05))  + 
  stat_smooth(method="glm", method.args=list(family="binomial"), se=TRUE)+theme_minimal()

plot2<-ggplot(silv.data, aes(x=flower_time, y=pro)) + geom_point(shape=1, position=position_jitter(width=.05,height=.05)) + 
  stat_smooth(method="glm", method.args=list(family="binomial"), se=TRUE)+theme_minimal()

plot3<-ggplot(silv.data, aes(x=pol, y=pro)) + 
  geom_point(shape=1, position=position_jitter(width=.05,height=.05)) + 
  stat_smooth(method="glm", method.args=list(family="binomial"), se=TRUE)+theme_minimal()

plot4<-ggplot(silv.data, aes(x=shade_bin, y=pro)) + 
  geom_point(shape=1, position=position_jitter(width=.05,height=.05)) + 
  stat_smooth(method="glm", method.args=list(family="binomial"), se=TRUE)+theme_minimal()

plot5<-ggplot(silv.data, aes(x=height, y=pro)) + 
  geom_point(shape=1, position=position_jitter(width=.05,height=.05)) + 
  stat_smooth(method="glm", method.args=list(family="binomial"), se=TRUE)+theme_minimal()

grid.arrange(plot1, plot2,plot3,plot4,plot5, ncol=2)
@
\caption{Silvics binomial plots}
\end{figure}

\end{document}