\documentclass[12pt]{article}
\usepackage[top=1.00in, bottom=1.0in, left=1.1in, right=1.1in]{geometry}
\renewcommand{\baselinestretch}{1.1}
\usepackage{graphicx}
\usepackage{natbib}
\usepackage{amsmath}
\bibliographystyle{..//refs/styles/besjournals.bst}
\renewcommand{\thetable}{S\arabic{table}}
\renewcommand{\thefigure}{S\arabic{figure}}
\usepackage{xr-hyper}
\externaldocument{shortest_reconciling.tex}

\def\labelitemi{--}
\parindent=24pt
\title{Supplement: Reconciling historic hypotheses regarding flower-leaf sequences in temperate forests for fundamental and global change biology}

\begin{document}
\maketitle

\subsection*{Methods}
\subsubsection*{Climate Change and FLS:}
To evaluate how FLS patterns have changed over time in association with climate change we obtained phenological data for four European woody plant species with long term phenology records of both flower (BBCH 60) and leafout phenology (BBCH 11) from the Pan European Phenological Database \citep{PEP725}. We restricted the data set to include only stations with more than 50 years worth of data. For each species, we modeled the number of days between flowering and leafing as a function of time, using a hinge model with 1980 as break point in accordance with climate change models of \citet(). \textit{Lizzie do you have any citations for hinge models?} For each species, we display the pre-1980 mean and 95\% credible intervals of the time between flowering and leafing and the post-1980 change in mean time between phenophases that can be driven by climate change.

\subsubsection*{Defining FLS with MTSV and USFS data}
For these two, categorical, species level case studies, we converted verbal descriptions of flower-leaf sequences into a binary response variable. For our more inclusive "functional" definition of hysteranthy which allows for overlap between phenophases, we included species entries with descriptions \textit{"flowers before the leaves"}, \textit{"flowers before or with leaves"} and textit{"flowers with leaves"} as hysteranthous. Our more restrictive "physiological" hysteranthy definition only included species described as \textit{"flowers before the leaves"} as hysteranthous.\\

\noindent For modeling trait associates we chose three predictors to represent the three major FLS hypothesis; pollination syndrome, average flowering time and minimum precipitation levels across the species range. We obtained pollination syndrome and average flowering time information directly from the respective data sources and estimates of minimum precipitation across range from the USDA/NRCS Conservation Plants Characteristics database. We coded pollination syndrome as binary, biotic- or wind-pollinated and assigned known ambophilous species in the genus \textit{Salix} to the ancestral, biotic-pollinated, state of angiosperms. We re-coded flowering time as the average of the range of months of flowering reported in each data source.\\

\noindent For these case studies, we modeled associations between hysteranthy and the trait predictors with logistical regressions in phylogenetic generalized linear modeling framework \citep{Ives2010} using the R package ``phylolm" \citep{Ho2014}.Our models incorporated a published angiosperm phylogenetic tree \citep{Zanne2013} pruned to match the species list for each case study. Species found in the trait data set but not in the original phylogenetic tree were added to the pruned tree at the generic root. In total 32 species were added to the generic roots for the MTSV data set and eight for the USFS data set. We visualize phylogentic patterning of FLS across the tree of each case study (Fig. \ref{fig:phylogeny}) and we report the phylogentic signal for each of the categorical case studies (Tab. \ref{tab:Dstats}).\\

\noindent We ran the models with 599 bootstrapped re-sampling iterations for each data set \citep{Wilcox2010}. We standardized all predictors by subtracting the mean and dividing by two standard deviations to allow for a reasonable comparison of effect sizes between the binary and continuous predictors in this model \citep{Gelman2007}. To assess the phylogenetic structure of hysteranthous flowering, we used the Caper package \citep{Orme2013} to calculate a phylogenetic D statistic \citep{}.\\
%Nacho is this actually what the D statistic is called? Do you know a citatation for it?

\subsubsection*{Harvard Forest models}
For each individual tree per year in the data, we calculated the time between flowers opening and leaves reaching 75\% of their final size. To compare the inference from between catagorical and continuous measure of FLS we re-coded the HF continuous FLS measures as binary responses with positive values coded as hysteranthous and negative values as seranthous. These models used the same predictors as the MTSV and USFS datasets, except that we estimated the average flowering time directly from the HF data. All models the R package ``brms" \citep{Burkner2018} to estimate the relationship between FLS and the predictors with a phylogenetic mixed model in a Bayesian framework \citep{}. We ran each model with weak priors, a warmup of 3000 iterations and 4000 sampling iterations. As our primary goal was to directly compare the effects each predictor we standardized these variables to allow for a reasonable comparision between them {\citep{Gelman2006}. \\

\noindent To test examine the relationship between inter-annual variation in FLS and precipitation, we obtained precipitation records from the Shaler meteorological station at Harvard Forest \citep{}. We modeled the association between FLS variatation and annual precipiation with a complete pooling model. We also ran a model testing for interactions between the effects of annual precipitation and pollination syndrome on FLS.  As above, these models run with weak priors, a warmup of 3000 iterations and 4000 sampling iterations.\\

The three Harvard Forest models are detailed below:\\
\begin{enumerate}
\item \underline{Categorical model}:\\
\item \underline{Continuous model}:\\
y_i &= \alpha_{sp[i]} + \beta_{pollination syndrome} + \beta_{flowering time} + \beta_{min. precipitation} +\beta_{pollination syndrome}:\beta_{flowering time}+\beta_{pollination syndrome}:\beta_{min. precipitation}+ \beta_{flowering time}:\beta_{min. precipitation} + \epsilon_i\\
\epsilon_i & \sim N(0,\sigma^2_y) \\ %I Think this is wrong and should reflect the phyogeny

\noindent The $\alpha$ was modeled at the species level, as follows:\\
\alpha_{sp} & \sim N(\mu_{\alpha}, \sigma_{\alpha}) \\

\end{enumerate}
\indent We calculated the marginal effects for the Harvard Forest continuous model using the R-package ``ggeffects" \citep{Ludecke2018}.\\

\noindent Though we make broad comparisons between the HF and MTSV/USFS case studies, differences in data structure between the datasets required us to use alternative modeling frameworks. The MTSV and USFS data provide one response variable for each species while the HF data contains intra-specific differences in FLS, providing several different response values per species. The current phylogenetic generalized linear model framework can only fit models with one response value per species, while the phylogenetic mixed model in brms over-fits models with this kind of data structure (Paul Burkner, personal communication) and performs better on multi-response per species datasets like HF. We ran both model types on each case study and while they do yield different absolute estimates, the patterns we found were consistent across each framework, and we report results from the most acurate model for each dataset.\\
\section*{Supplimental Tables and Figures}

\begin{figure}[h!]
    \centering
 \includegraphics[width=\textwidth]{..//MTSV_USFS.jpeg} 
    \caption{\textbf{Mean estimates of the effects of FLS predictors on the likehilood a species is hysteranthous vary across datasets and definitions of FLS.}  We used phylogenetic adjustments and standardized units to make a basic comparison of two datasets and classes (physiological= no overlap between flowering and leafing, functional= moderate overlap) of FLS. While there is some agreement accross models (strong effects of flowering time, no consistant effect interactions between predictors), the effect of other predictors (pollination syndrome, water dynamics) were highly sensitive to how data were defined, biasing any inference from models and compromising the ability to validate the exisitng FLS hypotheses. Lines represent 95\% bootstrap intervals.}
    \label{fig: muplots.USMT}
\end{figure}

\begin{figure}[h!]
    \centering
 \includegraphics[width=\textwidth]{..//HarvardForst/HFmeans_expanded.jpeg} 
    \caption{\textbf{}}
    \label{fig:HFmeans}
\end{figure}

<<Code_chunk_Minimal_example, results='asis', echo=FALSE>>=
rm(list=ls()) 
options(stringsAsFactors = FALSE)
graphics.off()
#setwd("~/Documents/git/proterant/sub_proj")
library(xtable,quietly=TRUE)
library(caper,quietly=TRUE)

#read in data
mich.data<-read.csv("..//MTSV_USFS/michdata_final.csv")
mich.tre<-read.tree("..//MTSV_USFS/michtre_final.tre")

silv.data<-read.csv("..///MTSV_USFS/silvdata_final.csv")
silv.tre<-read.tree("..//MTSV_USFS/silvtre_final.tre")
mich.tre$node.label<-NULL
silv.tre$node.label<-NULL
d<-comparative.data(mich.tre,mich.data,name,vcv = TRUE,vcv.dim = 2, na.omit = FALSE)
Phylo.Pro.phys<-phylo.d(d, binvar=pro3) 

##functionalhysteranthy
PhyloPro.funct<-phylo.d(d,binvar=pro2)



d.silv<-comparative.data(silv.tre,silv.data,name,vcv = TRUE,vcv.dim = 2, na.omit = FALSE)
silv.Pro.phys<-phylo.d(d.silv, binvar=pro3) 
silv.Pro.funct<-phylo.d(d.silv,binvar=pro2)



df <- data.frame(Dataset = c("MTSV","MTSV","USFS","USFS"),
                 category  = c("Functional","Physiological","Functional","Physiological"),
                 D = c(PhyloPro.funct$DEstimate,Phylo.Pro.phys$DEstimate,silv.Pro.funct$DEstimate,silv.Pro.phys$DEstimate))

strCaption <- paste0("\\textbf{Table 1} D statistics for the inter-specific FLS datasets with different classifications of hysteranthy")
table1<-xtable(df, digits=2, caption=strCaption, label="tab:Dstats") 
align(table1) <- "|ll|l|l"
print(table1,
      include.rownames=FALSE, #Don't print rownames

      caption.placement="bottom") 
      
     
                        
      
                 
             


@

\begin{figure}[H]
<<Code_chunk_Minimal_example3, results='asis',Fig=TRUE, echo=FALSE,message=FALSE,warning=FALSE,out.width='7.5in'>>=
rm(list=ls()) 
options(stringsAsFactors = FALSE)
#setwd("~/Documents/git/proterant/sub_proj")


library(ggtree,quietly=TRUE)
library(gridExtra,quietly=TRUE)

mich.data<-read.csv("..//MTSV_USFS/michdata_final.csv")
mich.tre<-read.tree("..//MTSV_USFS/michtre_final.tre")

silv.data<-read.csv("..//MTSV_USFS/silvdata_final.csv")
silv.tre<-read.tree("..//MTSV_USFS/silvtre_final.tre")


mich.data$synth<-mich.data$pro2+mich.data$pro3
mich.data$synth2[which(mich.data$synth==0)] <- "always seranthous"
mich.data$synth2[which(mich.data$synth==1)] <- "transitional"
mich.data$synth2[which(mich.data$synth==2)] <- "always hysteranthous"

tr <-mich.tre

par(mar=c(0,0,0,0))

dd <- data.frame(taxa  = mich.data$name, hysteranthy = mich.data$synth2 )

p<-ggtree(tr,layout="radial")
p <- p %<+% dd +geom_tippoint(aes(color=hysteranthy,shape=hysteranthy),size=2)
p<-p+theme(legend.position = "none")



silv.data$synth<-silv.data$pro2+silv.data$pro3
silv.data$synth2[which(silv.data$synth==0)] <- "always seranthous"
silv.data$synth2[which(silv.data$synth==1)] <- "transitional"
silv.data$synth2[which(silv.data$synth==2)] <- "always hysteranthous"

#### make a tree for svics

tr1 <-silv.tre

dd1 <- data.frame(taxa  = silv.data$name, hysteranthy = silv.data$synth2 )


q<-ggtree(tr1,layout="radial")
q <- q %<+% dd1 +geom_tippoint(aes(color=hysteranthy,shape=hysteranthy),size=2)

q<-q+theme(legend.position="bottom")


ggpubr::ggarrange(p,q,ncol=2,legend="bottom",common.legend = TRUE)

@
   
  \caption{\textbf{Phylogenetic structure of FLS in MTSV and USFS varies significantly depending on how FLSs are defined.} Many species get re-assigned to either hysteranthy or seranthy depending on whether FLS is defined functionally (partial overlap between flowering and leafing allowed) or physiologically (no overlap between flowering and leafing allowed) (blue squares). This modeling choice dramatically alters FLS patterning across the tree, resulting in an unstable phylogentical signal for this trait.}
    \label{fig:phylogeny}
    \end{figure}
  
  
\pagebreak
\bibliography{..//refs/hyst_outline.bib}
\end{document}
