\documentclass{article}
\usepackage{Sweave}
\usepackage{tabularx}
\usepackage{geometry}
\geometry{margin=.5in}
\usepackage{enumerate}
\usepackage{subfig}
\usepackage[demo]{graphicx}
\makeatletter
\setlength{\@fptop}{0pt}
\makeatother
\begin{document}
\SweaveOpts{concordance=TRUE}
%updated May 16 2016
\begin{figure}[!tbp]
  \centering
  \fbox{\subfloat[Physioloical Hysteranthy: Average floral and foliar budburst]{\includegraphics[width=0.5\textwidth]{HF_phys.jpeg}\label{fig:f1}}
  \hfill
  \subfloat[Functional Hysteranthy: Average first flowering and leaves expansion to 75 percent]{\includegraphics[width=0.5\textwidth]{HF_funct.jpeg}\label{fig:f2}}}
  \caption{Average Floral and Leaf Phenology at Harvard Forest 1990-2014. As seen through comparision, species classifications of hysteranthy vary greatly depending on whether physiologicial or functional definitions are used.}
\end{figure}

\begin{figure}[!tbp]
  \centering
 \fbox{ \subfloat[Acer rubrum]{\includegraphics[width=0.3\textwidth]{ACRU.jpeg}\label{fig:f3}}
  \hfill
  \subfloat[Quercus rubra]{\includegraphics[width=0.3\textwidth]{QURU.jpeg}\label{fig:f4}}
  \subfloat[Betula populifolia]{\includegraphics[width=0.3\textwidth]{BEPO.jpeg}\label{fig:f5}}}
  \caption{Annual variation in degree of hysteranthy for individals in Harvard forest 1900-2001.}
\end{figure}

\begin{figure}[h!]
  \centering
   \fbox{ \includegraphics[width=0.95\textwidth]{circle_tree.jpeg}}
   \caption{Phylogenetic relationships between the 194 species included in this analysis. Hysteranthous species are indicated with blue traiangles and non-hysteranthous with red circles.}
\end{figure}

\begin{figure}[!tbp]
  \centering
 \fbox{ \subfloat[Full Dataset]{\includegraphics[width=0.5\textwidth]{funct_effect_fill.jpeg}\label{fig:f6}}
  \hfill
  \subfloat[Early flowering only]{\includegraphics[width=0.5\textwidth]{early_effectplot.jpeg}\label{fig:f7}}}
  \caption{Model estimated effect sizes and 95 resampling intervals for biological predictors of hysteranthy.  In both the full MTSV dataset and restricted dataset, wind pollination and early flowering are the strongest predictors.}
\end{figure}

\begin{figure}[h!]
  \centering
   \fbox{ \includegraphics[width=0.95\textwidth]{phys_effect_fill.jpeg}}
   \caption{Suppliment: Model estimated effect sizes and 95 resampling intervals for biological predictors of hysteranthy using MTSV statement "flowers before leaves" only to define hysteranthy. There is no change in direction of the significant predictors from the classification scheme we used. }
\end{figure}



\end{document}