\documentclass{article}
\usepackage{Sweave}
\usepackage{float}
\usepackage{graphicx}
\usepackage{tabularx}
\usepackage{siunitx}
\usepackage{mdframed}
\usepackage{cite}
\usepackage{natbib}
\bibliographystyle{..//refs/styles/besjournals.bst}
\usepackage[small]{caption}
\setkeys{Gin}{width=0.8\textwidth}
\setlength{\captionmargin}{30pt}
\setlength{\abovecaptionskip}{0pt}
\setlength{\belowcaptionskip}{10pt}
\topmargin -1.5cm        
\oddsidemargin -0.04cm   
\evensidemargin -0.04cm
\textwidth 16.59cm
\textheight 21.94cm 
%&\pagestyle{empty} %comment if want page numbers
\parskip 0pt
\renewcommand{\baselinestretch}{1.5}
\parindent 20pt

\newmdenv[
  topline=true,
  bottomline=true,
  skipabove=\topsep,
  skipbelow=\topsep
  ]{siderules}
\usepackage{lineno}
\linenumbers

\begin{document}
\SweaveOpts{concordance=TRUE}
\title{ Flowering first: Hysteranthy is a signature of extreme early flowering and wind pollination in Eastern deciduous forest communities of North America: INTRODCTION ONLY}
\author{Daniel Buonaiuto, Ignacio Morales Castilla, Lizzie Wolkovich}
\maketitle{}
\section*{Introduction}

\indent Green is the color of spring \citep{Schwartz1998}, but any keen observer walking the Eastern deciduous forests of North America early in the season would readily notice that it is often the subtle reds and yellows of emerging tree flowers that are the first harbingers of the season. Why do some tree species seasonally flower before leafing out? This trait, known as hysteranthy,proteranthy or precocious flowering \citep{Heinig1899,} is apparent in many commercially and ecologically important woody plant species. Hysteranthy has been described as a characteristic flowering pattern in temperate deciduous forests of North America \citep{Rathcke1985}, and it has been suggested that this trait is critical for reproductive success \citep*{Spur1980,Whitehead1969}. \\
\indent However, despite its reputed importance and frequency of occurrence, there has been little direct, empirical investigation into the origins or significance of this pattern \citep*{Lechowiz1995}. This lack of explicit research attention may be attributed to fact that floral and leaf phenology have long been treated as disparate processes and rarely observed in tandem \citep{Wolkovich2014}, or the imprecise and variable usage of terms to describe this pattern in the literature \citep*{Dyer1953,Lamont2011}. If hysteranthy is indeed a widespread and critical trait for the reproduction of temperate tree species, it would be expected that it plays an important role in community dynamics, population cycles and life history evolution, and merits a deeper inquiry.\\
\par A detailed investigation of this pattern is of even greater importance in an era of global change in which significant alterations to the phenology, the timing of annual life cycle events, of many organisms have already been widely observed \citep*{Menzel2006}. Alterations to the hysteranthous pattern could have major effects on the demography and structure of temperate forest communities, but we have little understanding of the stability of hysteranthy in variable environmental conditions.\\
\indent The most common hypothesis for the seemingly high rate of occurrence of hysteranthy in temperate deciduous species is that this phenological pattern is an adaptation critical for wind pollination, with leafless flowering allowing for more effective pollen transfer \citep{Whitehead1969,Rathcke1985, Spurr1980}. While several studies found suggestive support for this hypothesis through the comparison of wind velocity and particle diffusion between leafless and full canopied forests \citep*{Brown1969,Niklas1985,Whitehead1969}, we are unaware of any studies that have either systematically evaluated the association between pollination syndrome and hysteranthous flowering, or investigated the fitness gains of hysteranthy directly.\\
\indent Despite the common adaptive interpretation of hysteranthy, evidence does not preclude it from being under weak to no direct selection. The hysteranthous pattern could simply be a by-product of other, independent selective regimes acting with differential strength on floral and foliate phenology. With this null model formulation, the hysteranthous pattern could simply be a necessary consequence of selection for extremely early flowering. A third possibility is that hysteranthy may also be a highly conserved trait, and the preponderance of this phenological pattern in the temperate zone is a product of phylogenetic representation of the region rather than an adaptive quality to the trait.\\
\indent It should be noted that hysteranthous flowering is common in other plant communities, such as such as the dry deciduous tropics \cite{Franklin2016} and among Mediterranean geophytes\citep{Marques2012}. Other hypotheses, related to insect viability \citep{Janzen1967} and water stress \citep{Franklin2016} have emerged from studies in these systems, but have not been broadly considered in the temperate zone. We are primarily interested in exploring hysteranthy in temperate forests and limit the scope of our analysis to the hypotheses relevant in this system.\\
\indent Here we evaluate the associations between hysteranthy and several other life history traits of temperate woody plant species. We combined phylogenetic information with compiled species-level data on hysteranthy, pollination syndrome, several related traits (shade tolerance, plant height, flowering time, duration of fruit maturation) pertinent to the established hypotheses.\\
\par Given wind-pollination efficiency hypothesis, we would expect wind pollination syndrome to be a strong predicted of hysteranthy. We might also expect that shade tolerance would increase the likelihood of hysteranthous flowering, as shade tolerant species are likely to be found in more dense forests, where the benefit of flowering before canopy closure would be accentuated. We also would predict an association between hysteranthy and increasing plant height, because the reduction wind speeds as a result of canopy closure would be most dramatic experienced in tall canopy species.\\
\indent If our null model is supported, we would expect to see no strong signal from the three predictors mentioned above. Instead, we would expect that early flowering would be the strongest predictor of hysteranthy. We may also expect to see this hypothesis reinforced by a relationship between longer fruit maturation times and hysteranthy, as fruit development has been suggested to be driver of early flowering \citep{Primack1987}. Finally, a strong phylogenetic signal, with no clear trend in the other predictors, would suggest that hysteranthy is an evolutionary conserved trait.

\end{document}