\documentclass{article}
\usepackage{Sweave}
\usepackage{float}
\usepackage{graphicx}
\usepackage{tabularx}
\usepackage{siunitx}
\usepackage{mdframed}
\usepackage{cite}
\usepackage{natbib}
\bibliographystyle{..//refs/styles/besjournals.bst}
\usepackage[small]{caption}
\setkeys{Gin}{width=0.8\textwidth}
\setlength{\captionmargin}{30pt}
\setlength{\abovecaptionskip}{0pt}
\setlength{\belowcaptionskip}{10pt}
\topmargin -1.5cm        
\oddsidemargin -0.04cm   
\evensidemargin -0.04cm
\textwidth 16.59cm
\textheight 21.94cm 
%&\pagestyle{empty} %comment if want page numbers
\parskip 0pt
\renewcommand{\baselinestretch}{1.5}
\parindent 20pt

\newmdenv[
  topline=true,
  bottomline=true,
  skipabove=\topsep,
  skipbelow=\topsep
  ]{siderules}
\usepackage{lineno}
\linenumbers

\begin{document}
\SweaveOpts{concordance=TRUE}
\title{ Flowering first: Hysteranthy is a signature of extreme early flowering and wind pollination in Eastern decidious forest communites of North America}
\author{Daniel Buonaiuto, Ignacio Morales Castilla, Lizzie Wolkovich}
\maketitle{}
\section*{Introduction}
\indent Green is the color of spring \citep{Schwartz1998}, but any keen observer walking the Eastern deciduous forests of North America early in the season would readily notice that it is often the subtle reds and yellows of emerging tree flowers that are the first harbingers of the season. Why do some tree species seasonally flower before leafing out? This trait, known as hysteranthy,proteranthy or precocious flowering \citep{Heinig1899,} is apparent in many commercially and ecologically important woody plant species. Hysteranthy has been described as a characteristic flowering pattern in temperate deciduous forests of North America \citep{Rathcke1985}, and it has been suggested that this trait is critical for reproductive success \citep*{Spur1980,Whitehead1969}. \\
\indent However, despite its reputed importance and frequency of occurrence, there has been little direct, empirical investigation into the origins or significance of this pattern \citep*{Lechowiz1995}. This lack of explicit research attention may be attributed to fact that floral and leaf phenology have long been treated as disparate processes and rarely observed in tandem \citep{Wolkovich2014}, or the imprecise and variable usage of terms to describe this pattern in the literature \citep*{Dyer1953,Lamont2011}. If hysteranthy is indeed a widespread and critical trait for the reproduction of temperate tree species, it would be expected that it plays an important role in community dynamics, population cycles and life history evolution, and merits a deeper inquiry.\\
\par A detailed investigation of this pattern is of even greater importance in an era of global change in which significant alterations to the phenology, the timing of annual life cycle events, of many organisms have already been widely observed \citep*{Menzel2006}. Alterations to the hysteranthous pattern could have major effects on the demography and structure of temperate forest communities, but we have little understanding of the stability of hysteranthy in variable environmental conditions.\\
\indent The most common hypothesis for the seemingly high rate of occurrence of hysteranthy in temperate deciduous species is that this phenological pattern is an adaptation critical for wind pollination, with leafless flowering allowing for more effective pollen transfer \citep{Whitehead1969,Rathcke1985, Spurr1980}. While several studies found suggestive support for this hypothesis through the comparison of wind velocity and particle diffusion between leafless and full canopied forests \citep*{Brown1969,Niklas1985,Whitehead1969}, we are unaware of any studies that have either systematically evaluated the association between pollination syndrome and hysteranthous flowering, or investigated the fitness gains of hysteranthy directly.\\
\indent Despite the common adaptive interpretation of hysteranthy, evidence does not preclude it from being under weak to no direct selection. The hysteranthous pattern could simply be a by-product of other, independent selective regimes acting with differential strength on floral and foliate phenology. With this null model formulation, the hysteranthous pattern could simply be a necessary consequence of selection for extremely early flowering. A third possibility is that hysteranthy may also be a highly conserved trait, and the preponderance of this phenological pattern in the temperate zone is a product of phylogenetic representation of the region rather than an adaptive quality to the trait.\\
\indent It should be noted that hysteranthous flowering is common in other plant communities, such as such as the dry deciduous tropics \cite{Franklin2016} and among Mediterranean geophytes\citep{Marques2012}. Other hypotheses, related to insect viability \citep{Janzen1967} and water stress \citep{Franklin2016} have emerged from studies in these systems, but have not been broadly considered in the temperate zone. We are primarily interested in exploring hysteranthy in temperate forests and limit the scope of our analysis to the hypotheses relevant in this system.\\
\indent Here we evaluate the associations between hysteranthy and several other life history traits of temperate woody plant species. We combined phylogenetic information with compiled species-level data on hysteranthy, pollination syndrome, several related traits (shade tolerance, plant height, flowering time, duration of fruit maturation) pertinent to the established hypotheses.\\
\par Given wind-pollination efficiency hypothesis, we would expect wind pollination syndrome to be a strong predicted of hysteranthy. We might also expect that shade tolerance would increase the likelihood of hysteranthous flowering, as shade tolerant species are likely to be found in more dense forests, where the benefit of flowering before canopy closure would be accentuated. We also would predict an association between hysteranthy and increasing plant height, because the reduction wind speeds as a result of canopy closure would be most dramatic experienced in tall canopy species.\\
\indent If our null model is supported, we would expect to see no strong signal from the three predictors mentioned above. Instead, we would expect that early flowering would be the strongest predictor of hysteranthy. We may also expect to see this hypothesis reinforced by a relationship between longer fruit maturation times and hysteranthy, as fruit development has been suggested to be driver of early flowering \citep{Primack1987}. Finally, a strong phylogenetic signal, with no clear trend in the other predictors, would suggest that hysteranthy is an evolutionary conserved trait.

\section*{Methods}
\subsection*{Defining Hysteranthy}
\indent The most detailed data about hysteranthy come from qualitative descriptions in regional Flora and botanical guidebooks, such as \textit{"Flowers: Before the leaves."} or \textit{"Flowers: When leaves are half grown."}\citep{Barnes2014}. These kinds of qualitative verbal descriptors are inherently ambiguous and incompatible with our current, more quantitative observation standards. Differences in interpretation of these descriptors would radically change which species are categorized as hysteranthous.\\
\indent We evaluted the sensativity of hysteranthous classification to interpretation using published phenological observations from Harvard Forest in Petersham, Massachusetts from 1990-2015 \citep{OKeefe2015}. We plotted the mean leaf and floral budburst over the 25 year period for the 37 species included in the data set. Any species in which flower burst occured earlier we classified as hysteranthous. We then plotted the mean "flowers open" and  "leaf expansion reaches 75 percent of full size" phenophases, classifying species with flowers open before leaf exansion reached 75 percent of full sized as hysteranthous.\\ 
\indent As can bee seen in Figure 1, this choice regarding the definition of hysteranthy greatly impacts which species are classified as such. We suggest that an appropriate empirical definition of hysteranthy is largely dependent on which hypotheses are of interest. Because the focus of this paper is on temperate forests communities and the relevant hypotheses address pollination and reprodictive processes, here we define hysteranthy in line with figure 1b, to include species with open flowers during the early part of leaf expansion.\\
\subsection*{Data}
\indent We obtained species level descriptions of floral-foliate sequences and trait information from the regional guidebook Michigan Trees \citep{Barnes2004} and its companion volume Michigan Shrubs and Vines \citep{Barnes2016}, hereafter: MTSV. We investigated several other floras and monographs for inclusion in our analysis, but we found no other with comparably high levels of completeness of phenological descriptions. The complete list of sources we evaluated can be found in the Supplement. While MTSV describes woody plants found in Michigan, these communities bear a strong resemblance to forest communities of the Northeastern United States in general, and can serve as a reasonable model for the whole region.\\ 
\indent We coded all traits of interest as binary predictors. In keeping with our definition of hysteranthy, entries \textit{"flowers: before the leaves"}, \textit{"flowers: before or with leaves"} and textit{"flowers: with leaves"}  Pollination syndrome was coded as wind or animal pollinated with known ambophilous species coded as to the ancestral, animal pollinated, state of angiosperms. For shade tolerance we collapsing descriptions "moderately, or medium shade tolerant", "tolerant" and "very tolerant" to "tolerant". Flowering phenology was determined as average the range of months reported in the data, and fruit maturation time was determine by subtracting the average flowering time from average dispersal time. We used the maximum height reported in the data.  In total, 196 woody species were included in our analysis.\\
\subsection*{Statistical analysis}
\indent To investigated the phylogenetic signal of hysteranthy and control for phylogenetic structure in our dataset, we used a published angiosperm phylogenetic tree \citep{Zanne2013} pruned to match the species list from the MTSV data. Species found in the trait dataset but not in the original phylogenetic tree were added to the pruned tree at the genus level root. In total 32 species were added to the generic roots. To assess the phylogenetic structure in the trait of hysteranthy and the other binary predictors, we used Caper package \citep{Orme2013} to calculate a phylogenetic D statistic. To calculate the phylogenetic signal in our continuous predictors height, flowering time and development time, we used the phytools package \citep{} to calculate a Pagel's lambda value.  \\
\indent To investigate trait associations of hysteranthy, we used phylogenetic generalized linear modeling framework \citep{Ives2010} to build a logistical regression model corrected for phylogenetic structure using the R package phylolm \citep{Ho2014}. The model was run with 599 bootstrapped re-sampling iterations for each dataset \citep{Wilcox2000}. Continuous predictors were rescaled by subtracting the mean and dividing by two standard deviations to allow for a reasonable comparison of effect sizes between the binary and continuous predictors in this model \citep{Gelman2007}.\\
\indent To investigate the sensitivity of our analysis to alternative definitions of hysteranthy , we also built a model using a physiological definition of hysteranthy in which only the descriptor \textit{"flowers: before leaves"} was coded as hysteranthous and all other descriptors were coded as non-hysteranthous. The results from this model can be found in the Supplement.\\
\indent Because hysteranthous species must flower before their leaves, they can never flower late in the season. To evaluate whether hysteranthous species flower uniquly early compared to early flowering non-hysteranthous species, we re-ran our model on a restricted dataset which only included species that flowered between mid-March and mid-May.\\
\indent To aid in the interpretation of our model's main effects, we ran average predictive comparisons qunatify the change in likelihood of hysteranthy given a change in pollination syndrome and a one month advance in flowering in the early spring.
\section*{Results}

\indent In our analysis, 103 out of 196 species were classified as hysteranthous. The phylogenetic signal for hysteranthy was low (see figure 2) with a D statistics of 0.06. In contrast,the D statistic for pollination syndrome, a trait known to be highly phylogenetically structured \citep{}, was -0.491472, confirming a very strong phylogenetic signal. Flowering time showed a strong phylogenetic structuring with a lambda value of 0.92, while in fruit maturation duration, the phylgenetic signal was weaker with a lambda value of 0.52.\\
\indent Average timing of flowering was the strongest predictor of hysteranthy, with the likelihood of hysteranthy increasing substantially with earlier flowering. Pollination syndrome also had a strong effect, with the likelihood of hysteranthy increasing in wind pollinated taxa (see figure 2a). There was also a weak effect of shorter seed duration time increasing the likelihood of hysteranthy. None of the other predictors included in the model has substantial effects.
\indent Early flowering remained a significant effect even among early flowering species only with likelihood of hysteranthy still increased substantially with earlier flowering in this resticted dataset (see figure 2b).\\


\section*{Discussion}
\begin{itemize}
\item Our finding suggest that hysteranthous flowering is strongly associated with wind pollination and early flowering.
  \begin{itemize}
  \item Average predictive comparisons: a species that is wind pollinated is 41 percent more likely to be hysteranthous than an insect pollinated species. A species flowering in April is 22 percent more likely to be hysteranthous than one flowering in May.
\item These results are consistent with the the wind pollination hypothesis, but cannot identify the mechanism nor conclusively suggest hysteranthy is adaptive for fitness. 
\end{itemize}
  \item The most likely adaptive benefit from hysteranthous flowering would be a reduction in pollen filtration by non-floral structures. 
  \begin{itemize}
  \item Present Tauber study
  \item The reduction in pollen filtration could act on male fitness, female fitness or both.  
  \end{itemize}
\item For male fitness, less pollen filtration would increase the likelyhood of long distance pollen dispersal.
\begin{itemize}
  \item confirmed by Brown1969. 
  \item also wind speeds are higher when leafless, compounding this effect.
  \end{itemize}
\item For female fitness less pollen filtration reduces the likelihood of pollen limitation.
\begin{itemize}
\item Pollen limitation has been show to be more common in trees than other plant taxa    \citep{Larson2000}, but studies of pollen limitation in wind pollinated taxa are limited   \citep{Knight2005}.
 \item As far back as Darwin, it has been doctrinal that wind pollinated taxa produce an over abundance of pollen \citep{Friedman2009}, but recently, several studies have suggested the pollen and pollen dispersal limitation in wind pollinated taxa may be more prevalent than once thought \citep{Koenig2003}. 
\item Research is beginning to address the relationship between phenology, pollen limitation and reproductive output in wind pollinated species \citep*{Koenig2012, Koenig2015,Bogdziewicz2017}, but these studies tend to focus on the absolute timing and duration of the flowering season, rather than the timing of flowering relative to leaf phenology.
\end{itemize}
\item A comparative study, directly measuring pollen dispersal distances, or the frequency of pollen limitation in hysteranthous and non-hysteranthous taxa would be instructive.
\end{itemize}
\indent Until these fitness benefits are evaluated directly, we must consider the major implication of the functional hypotheses of hysteranthy, which is that the leafless period of flowering is critical for the reproductive success of these species. Therefore, we would expect that any substantial shifts in timing or duration of the hysteranthous period could have significant effects on the reproductive success of hysteranthous species. Both floral and foliate phenology respond to interactions between temperature and photoperiod \citep{Forrest2010}, and as such, variablility in these environmental cues affect the phenological response.\\
\begin{itemize}
\item There is a large body of models, observations and experiments about the empirical response of floral and foliate phenology to changing environmental conditions, but little work has been done to evaluate the synchrony of divergence of the responses between phenophases. These relative responses should be explored in 2 ecologically contexts: Interannual variability and long term climate change.
\item Interannual variability
\begin{itemize}
\item Variability in hysteranthy could affect variability in reproductive output. Masting
\item We don't have a good sense of what typical variability is. 
\item We should consider hysteranthy a continuous rather than binary trait.
\end{itemize}
\item It is also feasible that significant changes in seasonal temperatures associated with anthropogenic climate change could dramatically alter hysteranthous flowering patterns.
\begin{itemze}
\item If cure responses are different between phenophases, we could see changes in this pattern. If it is critical for reproduction, this could have negative demographic effects.
\item We don't know the degree of independence or constraint to assess this threat.
\end{itemize}
\end{itemize}
\indent In conclusion, our analysis suggests that in North American temperate forest, hysteranthy is common, lacks phylgenetic structure, and is associated with a wind pollination syndrome and extremely early flowering.
\begin{itemize} 
\item It may be critical for reproduction
\item contribute to reproductive variability and be threatened by climate change.
\item With the current existing body of research, we cannot assess the likelihood and impact of these scenarios.
\item we should do more research.
\end{itemize}

\end{document}
%\indent A second hypothesis, which we refer to as the "differential selection hypothesis", comes out of an application of life history theory. Phenological plasticity allows organisms to match life cycle events to the appropriate environmental conditions. For woody species in the temperate zones, the optimal timing for spring phenology is the product of a trade off between seasonal advance to maximize the length of the growing or reproductive season, and delay to minimize exposure to last season frost events \citep{Kramer1995}.One possible explanation for hysteranthous flowering patterns is that these selection pressures operate upon foliar and floral phenology with different strength.\\
%\indent Long lived perennials such at trees and shrubs invest more heavily in growth and survival (foliar resources), rather than reproduction (floral resources) \citep{Franco2004}. It follows that for such organisms, floral tissues would be more expendable than leaf tissue. Frost damage to developing leaves has been shown to reduce gross primary productive by up 14 percent \citep{Hufkins2012}, while it is unlikely that sporadic pollination droughts from losing a cohort of flowers would make a significant difference in the lifetime fitness of long lived organisms such trees \citep{Knight2005}. For these species, the benefits of early flowering, such as pollination efficiency or increasing fruit development and dispersal time \citep{Primack1987}, out weigh the risk of late season frost exposure. This is less true for the more critical leaf tissue, and thus a more conservative, delayed phenological strategy is employed \citep{Lenz2013}.\\

